dellaert_acco_booklist_homepage:
    pattern: /
    defaults: { _controller: DellaertACCOBooklistBundle:Main:index, _locale: nl }

dellaert_acco_booklist_homepage_with_locale:
    pattern:   /{_locale}/
    defaults: { _controller: DellaertACCOBooklistBundle:Main:index, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_acco_booklist_course_material_overview:
    pattern: /{_locale}/course-material-overview
    defaults: { _controller: DellaertACCOBooklistBundle:Main:courseMaterialOverview, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_acco_booklist_command_schedule:
    pattern: /{_locale}/command-schedule
    defaults: { _controller: DellaertACCOBooklistBundle:Main:commandSchedule, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_acco_booklist_list_command_types_by_description:
    pattern:   /{_locale}/command-types-id-description
    defaults: { _controller: DellaertACCOBooklistBundle:Main:listCommandTypesByIdDescription, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_acco_booklist_list_schools_by_id_title:
    pattern:   /{_locale}/schools-id-title
    defaults: { _controller: DellaertACCOBooklistBundle:KULAPI:listSchoolsByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_acco_booklist_list_faculties_by_id_title_noid:
    pattern:   /{_locale}/faculties-id-title
    defaults: { _controller: DellaertACCOBooklistBundle:KULAPI:listFacultiesByIdTitle, _locale: nl }
    requirements:
        scid: \w+
        _locale: nl|en

dellaert_acco_booklist_list_faculties_by_id_title:
    pattern:   /{_locale}/faculties-id-title/{scid}
    defaults: { _controller: DellaertACCOBooklistBundle:KULAPI:listFacultiesByIdTitle, _locale: nl }
    requirements:
        scid: \w+
        _locale: nl|en

dellaert_acco_booklist_list_levels_by_id_title_noid:
    pattern:   /{_locale}/levels-id-title
    defaults: { _controller: DellaertACCOBooklistBundle:KULAPI:listLevelsByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_acco_booklist_list_levels_by_id_title:
    pattern:   /{_locale}/levels-id-title/{scid}/{fid}
    defaults: { _controller: DellaertACCOBooklistBundle:KULAPI:listLevelsByIdTitle, _locale: nl }
    requirements:
        scid: \w+
        fid: \d+
        _locale: nl|en

dellaert_acco_booklist_list_studies_by_id_title_noid:
    pattern:   /{_locale}/studies-id-title
    defaults: { _controller: DellaertACCOBooklistBundle:KULAPI:listStudiesByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_acco_booklist_list_studies_by_id_title:
    pattern:   /{_locale}/studies-id-title/{scid}/{fid}/{lid}
    defaults: { _controller: DellaertACCOBooklistBundle:KULAPI:listStudiesByIdTitle, _locale: nl }
    requirements:
        scid: \w+
        fid: \d+
        lid: \d+
        _locale: nl|en

dellaert_acco_booklist_list_programs_by_id_title_noid:
    pattern:   /{_locale}/programs-id-title
    defaults: { _controller: DellaertACCOBooklistBundle:KULAPI:listProgramsByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_acco_booklist_list_programs_by_id_title:
    pattern:   /{_locale}/programs-id-title/{scid}/{sid}
    defaults: { _controller: DellaertACCOBooklistBundle:KULAPI:listProgramsByIdTitle, _locale: nl }
    requirements:
        scid: \w+
        sid: \d+
        _locale: nl|en

dellaert_acco_booklist_list_stages_by_id_title_noid:
    pattern:   /{_locale}/stages-id-title
    defaults: { _controller: DellaertACCOBooklistBundle:KULAPI:listStagesByIdTitle, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_acco_booklist_list_stages_by_id_title:
    pattern:   /{_locale}/stages-id-title/{scid}/{pid}
    defaults: { _controller: DellaertACCOBooklistBundle:KULAPI:listStagesByIdTitle, _locale: nl }
    requirements:
        scid: \w+
        sid: \d+
        _locale: nl|en

dellaert_acco_booklist_list_courses_in_level_noids:
    pattern:   /{_locale}/courses-in-level
    defaults: { _controller: DellaertACCOBooklistBundle:KULAPI:listCoursesInLevel, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_acco_booklist_list_courses_in_level:
    pattern:   /{_locale}/courses-in-level/{scid}/{pid}/{phid}
    defaults: { _controller: DellaertACCOBooklistBundle:KULAPI:listCoursesInLevel, _locale: nl }
    requirements:
        scid: \w+
        phid: \d+
        sid: \d+
        _locale: nl|en

dellaert_acco_booklist_list_courses_by_groups_in_level_noids:
    pattern:   /{_locale}/courses-by-groups-in-level
    defaults: { _controller: DellaertACCOBooklistBundle:KULAPI:listCoursesByGroupsInLevel, _locale: nl }
    requirements:
        _locale: nl|en

dellaert_acco_booklist_list_courses_by_groups_in_level:
    pattern:   /{_locale}/courses-by-groups-in-level/{scid}/{pid}/{phid}
    defaults: { _controller: DellaertACCOBooklistBundle:KULAPI:listCoursesByGroupsInLevel, _locale: nl }
    requirements:
        scid: \w+
        phid: \d+
        sid: \d+
        _locale: nl|en