dellaert_acco_booklist_homepage:
    pattern: /
    defaults: { _controller: DellaertACCOBooklistBundle:Main:index, _locale: nl }

dellaert_acco_booklist_homepage_with_locale:
    pattern:   /{_locale}/
    defaults: { _controller: DellaertACCOBooklistBundle:Main:index, _locale: nl }
    requirements:
        _locale: nl|en