parameters:
#    dellaert_acco_booklist.example.class: Dellaert\ACCOBooklistBundle\Example

services:
#    dellaert_acco_booklist.example:
#        class: %dellaert_acco_booklist.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
